version: "3"
services: 
  node-app:
    # automating docker compose within a current directory
    build: .
    ports: 
      # list of open port 
      - "3000:3000"
    volumes:
      # the - siginifies a list  
      - ./:/app
      -  /app/node_modules
    
    environment: 
      - PORT=3000 
      
    # env_file: 
      # - ./.env_file